#!/usr/bin/env bash
# Build the selected AVD x86_64 kernel. Use --dry-run to print without compiling.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_ENV="${AVD_TARGET_ENV:-${ROOT_DIR}/out/target.env}"
DIST_DIR="${DIST_DIR:-${ROOT_DIR}/dist}"
JOBS="${JOBS:-$(nproc)}"
DRY_RUN=0
BUILD_SYSTEM="${BUILD_SYSTEM:-auto}"

usage() {
    cat <<'EOF'
Usage:
  bash build.sh --dry-run
  bash build.sh [-j N] [--dist-dir DIR] [--build-system auto|bazel|legacy]

The script reads out/target.env generated by prepare.sh.
Modern Android kernels such as common-android14-6.1 use Bazel/Kleaf.
Legacy branches such as common-android11-5.4 use build/build.sh.
EOF
}

run() {
    if [ "${DRY_RUN}" -eq 1 ]; then
        printf '[dry-run]'
        printf ' %q' "$@"
        printf '\n'
    else
        "$@"
    fi
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --dist-dir) DIST_DIR="$2"; shift 2 ;;
        --build-system) BUILD_SYSTEM="$2"; shift 2 ;;
        -j|--jobs) JOBS="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
    esac
done

if [ -f "${TARGET_ENV}" ]; then
    # shellcheck source=/dev/null
    . "${TARGET_ENV}"
else
    echo "WARNING: ${TARGET_ENV} not found. Run prepare.sh first for version-aware builds." >&2
fi

REPO_BRANCH="${AVD_REPO_BRANCH:-}"
KERNEL_VERSION="${AVD_KERNEL_VERSION:-}"

select_build_system() {
    if [ "${BUILD_SYSTEM}" != "auto" ]; then
        echo "${BUILD_SYSTEM}"
        return
    fi
    if [ -f "${ROOT_DIR}/common-modules/virtual-device/BUILD.bazel" ]; then
        echo "bazel"
    else
        echo "legacy"
    fi
}

find_bazel() {
    for candidate in "${ROOT_DIR}/tools/bazel" bazel bazelisk; do
        if [ -x "${candidate}" ] || command -v "${candidate}" >/dev/null 2>&1; then
            echo "${candidate}"
            return 0
        fi
    done
    return 1
}

configure_arm64_qemu_env() {
    host_arch="$(uname -m)"
    if [ "${host_arch}" = "aarch64" ] || [ "${host_arch}" = "arm64" ]; then
        if [ -d "${QEMU_LD_PREFIX:-/opt/aosp-x86_64-sysroot}" ]; then
            export QEMU_LD_PREFIX="${QEMU_LD_PREFIX:-/opt/aosp-x86_64-sysroot}"
        fi
    fi
}

build_with_bazel() {
    bazel_bin="$(find_bazel)" || {
        if [ "${DRY_RUN}" -eq 1 ]; then
            bazel_bin="${ROOT_DIR}/tools/bazel"
        else
            echo "ERROR: Bazel wrapper not found. Sync the full build tools or install bazel/bazelisk." >&2
            exit 1
        fi
    }
    mkdir -p "${DIST_DIR}"
    cd "${ROOT_DIR}"
    run "${bazel_bin}" run \
        --config=fast \
        --config=stamp \
        --lto=none \
        --jobs="${JOBS}" \
        //common-modules/virtual-device:virtual_device_x86_64_dist \
        -- --dist_dir="${DIST_DIR}"
}

build_with_legacy() {
    build_config="${BUILD_CONFIG:-common-modules/virtual-device/build.config.goldfish.x86_64}"
    if [ ! -f "${ROOT_DIR}/${build_config}" ]; then
        build_config="common-modules/virtual-device/build.config.virtual_device.x86_64"
    fi
    if [ ! -f "${ROOT_DIR}/${build_config}" ]; then
        echo "ERROR: no supported legacy build config found." >&2
        exit 1
    fi
    mkdir -p "${DIST_DIR}"
    cd "${ROOT_DIR}"
    configure_arm64_qemu_env
    run env \
        BUILD_CONFIG="${build_config}" \
        DIST_DIR="${DIST_DIR}" \
        LTO=none \
        ./build/build.sh -j"${JOBS}" YACC=/usr/bin/bison LEX=/usr/bin/flex
}

echo "=== AVD ReSukiSU kernel build ==="
echo "Kernel version : ${KERNEL_VERSION:-unknown}"
echo "Repo branch    : ${REPO_BRANCH:-unknown}"
echo "Build system   : $(select_build_system)"
echo "Dist dir       : ${DIST_DIR}"
echo "Jobs           : ${JOBS}"
echo ""

case "$(select_build_system)" in
    bazel) build_with_bazel ;;
    legacy) build_with_legacy ;;
    *) echo "ERROR: unsupported build system: ${BUILD_SYSTEM}" >&2; exit 2 ;;
esac
